// Bundle source files as strings: loading the Playground must never execute example code.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
const root = new URL('../docs/playground/examples/', import.meta.url);
const target = new URL('../docs/playground/playground_examples.js', import.meta.url);

export async function buildExampleBundle() {
  const files = [];
  const names = new Set();
  async function walk(relative = '') {
    const entries = await readdir(new URL(relative, root), {withFileTypes: true});
    entries.sort((a,b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    for (const entry of entries) {
      const path = relative + entry.name;
      if (entry.isDirectory()) await walk(path + '/');
      else if (entry.name.endsWith('.js')) {
        const name = entry.name.slice(0,-3);
        if (names.has(name)) throw new Error(`Duplicate example name: ${name}`);
        names.add(name);
        files.push({path: '/examples/' + path, name, data: await readFile(new URL(path, root), 'utf8')});
      }
    }
  }
  await walk();
  return '// Generated by scripts/build_playground_examples.mjs. Edit examples/**/*.js instead.\n' +
    'export const EXAMPLE_FILES = ' + JSON.stringify(files,null,2) + ';\n' +
    'export const EXAMPLES = Object.fromEntries(EXAMPLE_FILES.map(file => [file.name, file.data]));\n';
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const source = await buildExampleBundle();
  if (process.argv.includes('--check')) {
    if (await readFile(target,'utf8') !== source) throw new Error('Example bundle is stale; run node scripts/build_playground_examples.mjs');
  } else await writeFile(target, source);
}
