// The existing Analyzer dialog remains the source of truth for this static page.
import {readFileSync,writeFileSync} from 'node:fs';
const source=new URL('../docs/vgm_analyzer/index.html',import.meta.url);
const target=new URL('../docs/vgm_analyzer/support.html',import.meta.url);
const dialog=readFileSync(source,'utf8').match(/<dialog id="chipSupportDialog"[\s\S]*?<\/dialog>/)?.[0];
const start=dialog?.indexOf('<p>Playback and analysis');
const end=dialog?.lastIndexOf('</ul>');
if(start===undefined||start<0||end<0)throw new Error('Cannot locate Analyzer support table and notes');
const content=dialog.slice(start,end+5);
const html=`<!doctype html>
<!-- Generated by node scripts/build_analyzer_support.mjs. Edit the support dialog in index.html. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tetorica VGM Analyzer — Sound chip support</title>
<meta name="description" content="Supported sound chips in Tetorica VGM Analyzer: playback, channel controls, state display, Note-ish and exports, with chip combination and sample ROM limitations.">
<link rel="canonical" href="https://kyorohiro.github.io/hello_ymfm_wasm/vgm_analyzer/support.html">
<style>
body{font:16px/1.6 system-ui,sans-serif;margin:0;background:#faf8f3;color:#242424}main{max-width:1200px;margin:auto;padding:24px}a{color:#075d85}h1{line-height:1.2}.chip-support-scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;background:white}caption{text-align:left;font-weight:bold;padding:12px 0}th,td{border:1px solid #ccc;padding:10px;text-align:left;vertical-align:top}thead{background:#e8eeed}li{margin:10px 0}code{overflow-wrap:anywhere}
</style>
</head>
<body><main>
<nav><a href="./index.html">Open VGM Analyzer</a></nav>
<h1>Tetorica VGM Analyzer — Sound chip support</h1>
<p>This is the browser Analyzer's support table, also available in the app's Sound chip support dialog. It can be read without running the player or loading a music file.</p>
${content}
<h2>Check a specific file with the CLI</h2>
<p>Browser and CLI coverage can differ. To inspect the chips recognized in a file and the available operations with your installed CLI version, run:</p>
<pre><code>npx tetorica-vgm support song.vgz --json</code></pre>
<p><a href="https://github.com/kyorohiro/hello_ymfm_wasm/blob/main/CLI.md">CLI documentation</a></p>
</main></body>
</html>
`;
if(process.argv.includes('--check')){
 if(readFileSync(target,'utf8')!==html)throw new Error('Support page is stale. Run node scripts/build_analyzer_support.mjs');
 console.log('Static support page matches the Analyzer dialog.');
}else{writeFileSync(target,html);console.log('Wrote docs/vgm_analyzer/support.html');}
