// Start a static server for docs on port 8083, or set SHELL_TEST_URL.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{const context=await browser.newContext();await context.addInitScript(()=>{window.__TAURI_INTERNALS__={invoke:async()=>{}};});const page=await context.newPage();await page.goto(process.env.SHELL_TEST_URL||'http://localhost:8083/playground/index.html');await page.waitForFunction(()=>window.monaco?.editor?.getEditors().some(e=>e.getModel()?.uri.path.startsWith('/project/')));
const source=code=>page.evaluate(code=>monaco.editor.getEditors().find(e=>e.getModel()?.uri.path.startsWith('/project/')).setValue(code),code);
async function submit(text){await page.locator('#consoleTab').click();await page.locator('#shellInput').fill(text);await page.locator('#shellInput').press('Enter');}
async function command(text){const count=await page.locator('#shellOutput').textContent();await submit(text);await page.waitForFunction(old=>document.getElementById('shellOutput').textContent!==old&&document.getElementById('shellState').textContent!=='Running…',count);return page.locator('#shellOutput').textContent();}
await source(`const {fs,shell}=await import('tetorica:shell');await fs.writeText('/child.js',"const {shell}=await import('tetorica:shell'); console.log('CHILD', (await shell.execute(['pwd'])).stdout);");const result=await shell.execute(['js','/child.js']);if(result.code)throw Error(result.stderr);await fs.mkdir('/empty');await fs.writeBinary('/binary.bin',new Uint8Array([1,128,255]));`);
assert.match(await command('js /index.js'),/CHILD/);
await source(`const {fs}=await import('tetorica:shell');await fs.writeText('/dep.js','export const value=1');`);await command('js /index.js');
await source(`const {value}=await import('./dep.js');console.log('FRESH',value);`);assert.match(await command('js /index.js'),/FRESH 1/);await command(`write /dep.js 'export const value=2'`);assert.match(await command('js /index.js'),/FRESH 2/);
await page.evaluate(()=>window.__tetoricaAutosaveFlush());await page.reload();await page.waitForFunction(()=>window.monaco?.editor?.getEditors().some(e=>e.getModel()?.uri.path.startsWith('/project/')));assert.match(await command('ls /'),/empty\//);assert.match(await command('cat /binary.bin'),/binary/);
await source(`const {fs}=await import('tetorica:shell');await fs.readFile('/index.js');console.log('CAS_WAIT');await new Promise(r=>setTimeout(r,500));await fs.writeText('/index.js','bad overwrite');`);await submit('js /index.js');await page.waitForFunction(()=>document.getElementById('shellOutput').textContent.includes('CAS_WAIT'));await source('// human edit');await page.waitForFunction(()=>document.getElementById('shellState').textContent!=='Running…');assert.match(await page.locator('#shellOutput').textContent(),/File changed during script execution/);assert.equal(await page.evaluate(()=>monaco.editor.getEditors().find(e=>e.getModel()?.uri.path==='/project/index.js').getValue()),'// human edit');
await source('while(true){}');await submit('js /index.js');await page.waitForFunction(()=>document.getElementById('shellState').textContent==='Running…');await page.waitForTimeout(100);await page.locator('#shellStopButton').click();await page.waitForFunction(()=>document.getElementById('shellState').textContent==='Stopped.');await command('ls /');await page.locator('#shellInput').press('ArrowUp');assert.equal(await page.locator('#shellInput').inputValue(),'ls /');
await command(`write /cassette.metadata.js 'export default {"version":1,"license":"NONE","workType":"NONE"}'`);
await page.locator('#mainMenu').evaluate(e=>e.open=true);page.once('dialog',dialog=>dialog.accept('shell-test'));const downloaded=page.waitForEvent('download');await page.locator('#exportCassetteButton').click();const archivePath=await (await downloaded).path();await page.locator('#mainMenu').evaluate(e=>e.open=false);
// API is visible to the TypeScript language service.
await source(`const {fs}=await import('tetorica:shell');await fs.writeText('/hello.js','hello');`);
const typed=await page.evaluate(async()=>{const model=monaco.editor.getEditors().find(e=>e.getModel()?.uri.path==='/project/index.js').getModel();const worker=await (await monaco.languages.typescript.getJavaScriptWorker())(model.uri);return await worker.getQuickInfoAtPosition(model.uri.toString(),model.getValue().indexOf('writeText')+3);});assert.ok(typed?.displayParts?.some(part=>part.text==='writeText'));
for(const worker of [false,true]){await page.locator('#workerExecution').setChecked(worker);await source(`setBpm(120);liveLoop('shell-check',async()=>{await sleep(0.2);});`);assert.match(await command('play /index.js'),/Played \/index.js/);assert.equal(await page.locator('#runFileSelect').inputValue(),'/index.js');await page.locator('#stopButton').click();await page.waitForFunction(()=>!document.getElementById('stopButton').disabled);}
await source(`const {fs}=await import('tetorica:shell');console.log('DELAY_READY');await new Promise(r=>setTimeout(r,1500));await fs.writeText('/late.js','BAD');`);await submit('js /index.js');await page.waitForFunction(()=>document.getElementById('shellOutput').textContent.includes('DELAY_READY'));
await page.locator('#mainMenu').evaluate(e=>e.open=true);await page.locator('#newCassetteButton').click();await page.locator('#newCassetteDialog button[value=new]').click();await page.waitForTimeout(1800);assert.doesNotMatch(await command('ls /'),/late\.js/);assert.match(await command('ls /scripts'),/example\.js/);await command('js /scripts/example.js hi');assert.match(await page.locator('#shellOutput').textContent(),/Shell script:/);
const chooser=page.waitForEvent('filechooser');await page.locator('#mainMenu').evaluate(e=>e.open=true);await page.locator('#importCassetteButton').click();await (await chooser).setFiles(archivePath);await page.waitForFunction(()=>document.getElementById('status').textContent.includes('Loaded cassette'));assert.match(await command('ls /'),/empty\//);await source(`const {fs}=await import('tetorica:shell');console.log('ZIP_BYTES',Array.from(await fs.readFile('/binary.bin',{type:'binary'})).join(','));`);assert.match(await command('js /index.js'),/ZIP_BYTES 1,128,255/);
console.log(JSON.stringify({passed:true,nestedJs:true,freshImport:true,autosaveBinaryAndDirectories:true,zipBinaryAndDirectories:true,conflict:true,stopBusyWorker:true,history:true,types:true,playMainAndWorker:true,projectCancellation:true,starterSample:true}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
